project:
  type: website
  output-dir: docs

website:
  title: "Christine Cui - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Weekly Notes"
        menu:
        - href: weekly-notes/week-01-notes.qmd
          text: "Week 1: Course Introduction"
        - href: weekly-notes/week-02-notes.qmd
          text: "Week 2: Algorithmic Decision Making & Census Data"
        - href: weekly-notes/week-03-notes.qmd
          text: "Week 3: Data Visualization & Exploratory Analysis"
        - href: weekly-notes/week-03/week3_lab_exercise.qmd
          text: "In-Class Lab 3: Data Visualization and EDA"
        - href: weekly-notes/week-04-notes.qmd
          text: "Week 4: Spatial Data & GIS Operations in R"
        - href: weekly-notes/week-04/scripts/week4_inclass_practice.qmd
          text: "In-Class Lab 4: Spatial Operations with Pennsylvania Data" 
        - href: weekly-notes/week-05-notes.qmd
          text: "Week 5: Introduction to Linear Regression"
        - href: weekly-notes/week-06-notes.qmd
          text: "Week 6: Spatial Machine Learning & Advanced Regression"
        - href: weekly-notes/week-07-notes.qmd
          text: "Week 7: Model Diagnostics & Spatial Autocorrelation"
        - href: weekly-notes/week-09-notes.qmd
          text: "Week 9: Critical Perspectives on Predictive Policing"
        - href: weekly-notes/week-09/lab/predictive_policing_exercise.qmd
          text: "In-Class Lab 9: Predictive Policing - Technical Implementation"
        - href: weekly-notes/week-10-notes.qmd
          text: "Week 10: Logistic Regression for Binary Outcomes: The case of recidivism"
        - href: weekly-notes/week-10/script/In_Class_Exercise_Instruction.md
          text: "In-Class Lab 10: Georgia DOC Policy Advisory Challenge"
      - text: "Labs"
        menu:
        - href: labs/lab_0/lab0_template.qmd
          text: "Lab 0: Dplyr Basics"
        - href: labs/lab_1/assignment1_template.qmd
          text: "Lab 1: Census Data Exploration"
        - href: labs/lab_2/assignment2_template.qmd
          text: "Lab 2: Spatial Analysis and Visualization"
        - href: labs/lab_4/assignment4_template.qmd
          text: "Lab 4: Spatial Predictive Analysis"
      - text: "Midterm Project"
        menu:
        - href: midterm/Slides/CuiXinyuan_Presentation.qmd
          text: "Midterm Slides"
        - href: midterm/Appendix/CuiXinyuan_Appendix.qmd
          text: "Midterm Appendix"
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto